package com.example.service

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val flag: String,
    val nativeName: String
) {
    FRANCAIS("fr", "Français", "🇫🇷", "Français"),
    MOORE("mos", "Mooré", "🇧🇫", "Mòoré"),
    DIOULA("dyu", "Dioula", "🇧🇫", "Julakan"),
    ENGLISH("en", "English", "🇬🇧", "English")
}

object LanguageManager {

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.FRANCAIS to mapOf(
            "app_name" to "Wend-Lamita Services",
            "app_subtitle" to "Kiosque Mobile Money & Commerce",
            "login_title" to "Authentification Sécurisée",
            "login_subtitle" to "Connectez-vous pour ouvrir la caisse",
            "enter_pin" to "Entrez votre code PIN (4 chiffres)",
            "biometric_login" to "Connexion par Empreinte",
            "touch_sensor" to "Touchez le capteur pour déverrouiller",
            "role_admin" to "Administrateur",
            "role_gerant" to "Gérant",
            "role_cashier" to "Caissier",
            "login_button" to "Ouvrir la Caisse",
            "switch_to_password" to "Connexion Nom / Mot de passe",
            "switch_to_pin" to "Connexion par Code PIN",
            "nav_dashboard" to "Accueil",
            "nav_mobile_money" to "Mobile M.",
            "nav_cni" to "Registre CNI",
            "nav_boutique" to "Boutique",
            "nav_debts" to "Dettes",
            "nav_ai" to "Assistant IA",
            "nav_reports" to "Bilan",
            "nav_admin" to "Admin & Z",
            "nav_subscription" to "Abonnement Pro",
            "deposit" to "Dépôt",
            "withdrawal" to "Retrait",
            "transfer" to "Transfert",
            "airtime" to "Achat Crédit",
            "sale" to "Vente Boutique",
            "amount" to "Montant (FCFA)",
            "phone" to "Numéro de Téléphone",
            "client_name" to "Nom du Client",
            "client_cni" to "N° Pièce d'identité (CNIB/Passeport)",
            "fee" to "Frais client",
            "commission" to "Commission Kiosque",
            "execute_transaction" to "Valider la Transaction",
            "dial_ussd" to "Lancer USSD Opérateur",
            "print_receipt" to "Imprimer Ticket Reçu",
            "share_whatsapp" to "Envoyer sur WhatsApp",
            "cni_scan_title" to "Numérisation Pièces d'identité",
            "cni_scan_btn" to "Scanner une Pièce (CameraX)",
            "cni_gallery_btn" to "Importer de la Galerie",
            "pos_cart" to "Panier",
            "pos_total" to "Total à Payer",
            "pos_checkout" to "Encaisser la Vente",
            "debts_title" to "Carnet de Crédit & Créances",
            "send_reminder" to "Rappel WhatsApp",
            "z_closure_title" to "Clôture de Caisse Journalière (Rapport Z)",
            "physical_cash" to "Comptage Espèces Réel",
            "theoretical_cash" to "Solde Espèces Théorique",
            "cash_difference" to "Écart de Caisse",
            "premium_title" to "Abonnement Premium Wend-Lamita",
            "activate_by_tx" to "Activer par ID de Transaction",
            "tx_id_hint" to "Ex: OM260826.0945.A18 ou MM84920",
            "plan_pro" to "Forfait Pro Kiosque",
            "plan_enterprise" to "Forfait Entreprise VIP",
            "active_badge" to "ACTIF & VÉRIFIÉ",
            "logout" to "Fermer Session",
            "official_calculator" to "Calculateur Officiel des Frais"
        ),
        AppLanguage.MOORE to mapOf(
            "app_name" to "Wẽnd-Lamita Services",
            "app_subtitle" to "Ligdi nina la ra-yiri tʋʋma",
            "login_title" to "Kẽed-n-bãngre",
            "login_subtitle" to "Kẽes y code PIN n pʋɩ tʋʋmda",
            "enter_pin" to "Kẽes y PIN (bimbis 4)",
            "biometric_login" to "Bãngre ne nus-bĩngre",
            "touch_sensor" to "Sɩb nus-bĩng zĩiga",
            "role_admin" to "Kãsem-kãsenga",
            "role_gerant" to "Gérant",
            "role_cashier" to "Kaasier",
            "login_button" to "Pʋɩ Kaasa",
            "switch_to_password" to "Yʋʋre la gom-bi-solgre",
            "switch_to_pin" to "Code PIN kẽed-n-bãngre",
            "nav_dashboard" to "Sɩngrẽ",
            "nav_mobile_money" to "Ligdi Tʋʋma",
            "nav_cni" to "CNI Seb-kãsenga",
            "nav_boutique" to "Ra-yiri",
            "nav_debts" to "Sam-sebre",
            "nav_ai" to "IA Sõngda",
            "nav_reports" to "Kall Bilan",
            "nav_admin" to "Kãsemse & Z",
            "nav_subscription" to "Pro Kiosque",
            "deposit" to "Ligdi ningre",
            "withdrawal" to "Ligdi yiisre",
            "transfer" to "Ligdi tʋlsem",
            "airtime" to "Kredid daabo",
            "sale" to "Teed koosgo",
            "amount" to "Ligdi sõore (FCFA)",
            "phone" to "Telefɔn nimero",
            "client_name" to "Ned yʋʋre",
            "client_cni" to "CNIB / Paspor nimero",
            "fee" to "Frais ligdi",
            "commission" to "Kiosque riibo",
            "execute_transaction" to "Tʋʋmde lebg n tɩge",
            "dial_ussd" to "Tʋlse ne USSD",
            "print_receipt" to "Yiis Reçu sebre",
            "share_whatsapp" to "Tʋlse WhatsApp pʋgẽ",
            "cni_scan_title" to "CNI / Paspor Gesgo",
            "cni_scan_btn" to "Reeg CNI foto (CameraX)",
            "cni_gallery_btn" to "Yiis Foto Galerie pʋgẽ",
            "pos_cart" to "Teed Panier",
            "pos_total" to "Sõor fãa",
            "pos_checkout" to "Reeg Ligdi",
            "debts_title" to "Sam-sebre & Kũuni",
            "send_reminder" to "Tʋlse WhatsApp Tẽegre",
            "z_closure_title" to "Zaabr Kaas Paagr (Rapport Z)",
            "physical_cash" to "Nus ligdi kall",
            "theoretical_cash" to "Tʋʋm ligdi kall",
            "cash_difference" to "Ligdi bakre",
            "premium_title" to "Wẽnd-Lamita Pro Abo",
            "activate_by_tx" to "Yiis Abo ne Transaction ID",
            "tx_id_hint" to "Maka: OM260826.0945.A18 bɩ MM84920",
            "plan_pro" to "Pro Kiosque Plan",
            "plan_enterprise" to "Entreprise VIP Plan",
            "active_badge" to "A YÕODO BẼ",
            "logout" to "Paa tʋʋmda",
            "official_calculator" to "Ligdi Frais Kalekilator"
        ),
        AppLanguage.DIOULA to mapOf(
            "app_name" to "Wend-Lamita Services",
            "app_subtitle" to "Wari bila-la ni feereli yɔrɔ",
            "login_title" to "Donkɛ-yɔrɔ lakanina",
            "login_subtitle" to "I ka PIN kɛ kase dayɛlɛ kama",
            "enter_pin" to "I ka PIN nimɔrɔ dɔn (nimɔrɔ 4)",
            "biometric_login" to "Donkɛ ni bolokɔnɔbara ye",
            "touch_sensor" to "I bolo lafi yɔrɔ kan",
            "role_admin" to "Kuntigiba",
            "role_gerant" to "Gérant",
            "role_cashier" to "Kasiri",
            "login_button" to "Kase Dayɛlɛ",
            "switch_to_password" to "Tɔgɔ ni kumasungurun",
            "switch_to_pin" to "PIN nimɔrɔ donkɛ",
            "nav_dashboard" to "Sɔrɔli",
            "nav_mobile_money" to "Wari Baara",
            "nav_cni" to "Kɛrɛnkalisen Gafe",
            "nav_boutique" to "Feereyɔrɔ",
            "nav_debts" to "Juru Gafe",
            "nav_ai" to "AI Dɛmɛbaga",
            "nav_reports" to "Jateminɛ",
            "nav_admin" to "Kuntigi & Z",
            "nav_subscription" to "Pro Abonnema",
            "deposit" to "Wari bila",
            "withdrawal" to "Wari bɔ",
            "transfer" to "Wari ci",
            "airtime" to "Telefɔn kiredi san",
            "sale" to "Fɛn feere",
            "amount" to "Wari hakɛ (FCFA)",
            "phone" to "Telefɔn nimɔrɔ",
            "client_name" to "Jago-tigi tɔgɔ",
            "client_cni" to "Kɛrɛnkalisen / Pasipɔri",
            "fee" to "Sarali wari",
            "commission" to "Kioski sɔrɔ",
            "execute_transaction" to "Baara dafa",
            "dial_ussd" to "USSD kɔdi wele",
            "print_receipt" to "Sɛbɛ bɔ ka di",
            "share_whatsapp" to "A ci WhatsApp kan",
            "cni_scan_title" to "Kɛrɛnkalisen foto ta",
            "cni_scan_btn" to "Kɛrɛnkalisen Ja Ta (CameraX)",
            "cni_gallery_btn" to "Ja ta Galari kɔnɔ",
            "pos_cart" to "Feerefɛnw",
            "pos_total" to "Jate bɛɛ",
            "pos_checkout" to "Wari minɛ",
            "debts_title" to "Juru Gafe",
            "send_reminder" to "Hakilijigicili WhatsApp",
            "z_closure_title" to "Surɔ Kase Datugu (Rapport Z)",
            "physical_cash" to "Bolo kɔnɔ wari",
            "theoretical_cash" to "Baara kɔnɔ wari",
            "cash_difference" to "Wari farafara",
            "premium_title" to "Wend-Lamita Pro Abonnema",
            "activate_by_tx" to "A ladafa ni Transaction ID ye",
            "tx_id_hint" to "Misi: OM260826.0945.A18 walima MM84920",
            "plan_pro" to "Pro Kioski Plan",
            "plan_enterprise" to "Entreprise VIP Plan",
            "active_badge" to "A BƐ BAARA LA",
            "logout" to "Bɔ kase kɔnɔ",
            "official_calculator" to "Frais Jateden Kalan"
        ),
        AppLanguage.ENGLISH to mapOf(
            "app_name" to "Wend-Lamita Services",
            "app_subtitle" to "Mobile Money Kiosk & Store POS",
            "login_title" to "Secure Authentication",
            "login_subtitle" to "Sign in to open the register",
            "enter_pin" to "Enter your 4-digit PIN code",
            "biometric_login" to "Biometric Fingerprint Login",
            "touch_sensor" to "Touch sensor to unlock session",
            "role_admin" to "Administrator",
            "role_gerant" to "Store Manager",
            "role_cashier" to "Cashier Agent",
            "login_button" to "Open Register",
            "switch_to_password" to "Username & Password Login",
            "switch_to_pin" to "PIN Code Login",
            "nav_dashboard" to "Dashboard",
            "nav_mobile_money" to "Mobile Money",
            "nav_cni" to "ID KYC Registry",
            "nav_boutique" to "Store POS",
            "nav_debts" to "Credit Book",
            "nav_ai" to "AI Assistant",
            "nav_reports" to "Reports & P&L",
            "nav_admin" to "Admin & Z-Report",
            "nav_subscription" to "Pro Subscription",
            "deposit" to "Cash Deposit",
            "withdrawal" to "Cash Withdrawal",
            "transfer" to "Money Transfer",
            "airtime" to "Airtime Top-Up",
            "sale" to "Store Sale",
            "amount" to "Amount (FCFA)",
            "phone" to "Phone Number",
            "client_name" to "Customer Full Name",
            "client_cni" to "ID Document No. (CNIB/Passport)",
            "fee" to "Customer Fee",
            "commission" to "Kiosk Commission",
            "execute_transaction" to "Process Transaction",
            "dial_ussd" to "Execute USSD Code",
            "print_receipt" to "Print Thermal Receipt",
            "share_whatsapp" to "Send via WhatsApp",
            "cni_scan_title" to "ID Document Scanning",
            "cni_scan_btn" to "Scan ID (CameraX)",
            "cni_gallery_btn" to "Import from Gallery",
            "pos_cart" to "POS Cart",
            "pos_total" to "Grand Total",
            "pos_checkout" to "Checkout & Pay",
            "debts_title" to "Customer Credit & Debts",
            "send_reminder" to "Send WhatsApp Reminder",
            "z_closure_title" to "Daily Cash Z-Closure Report",
            "physical_cash" to "Physical Cash Count",
            "theoretical_cash" to "Theoretical System Cash",
            "cash_difference" to "Cash Variance",
            "premium_title" to "Wend-Lamita Pro Subscription",
            "activate_by_tx" to "Activate via Transaction ID",
            "tx_id_hint" to "Ex: OM260826.0945.A18 or MM84920",
            "plan_pro" to "Pro Kiosk Plan",
            "plan_enterprise" to "Enterprise VIP Plan",
            "active_badge" to "ACTIVE & VERIFIED",
            "logout" to "Lock & Sign Out",
            "official_calculator" to "Official Fee Calculator"
        )
    )

    fun getString(key: String, language: AppLanguage): String {
        return translations[language]?.get(key)
            ?: translations[AppLanguage.FRANCAIS]?.get(key)
            ?: key
    }
}

val LocalAppLanguage = compositionLocalOf { AppLanguage.FRANCAIS }

@Composable
fun tr(key: String): String {
    val currentLang = LocalAppLanguage.current
    return LanguageManager.getString(key, currentLang)
}
